name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.2
  - pytest>=7.0.0
  - scipy>=1.10.0
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3
